[package]
name = "binance-cli"
version = "0.0.1"
authors = ["unv Annihilator <unv-annihilator@users.noreply.github.com>"]

[dependencies]
clippy = { version = "*", optional = true }
binance = "~0.1.3"
clap = "~2.29.1"
chrono = "~0.4.0"